spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    servlet:
      multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 10MB
        file-size-threshold: 2MB

jwt:
  privateKey: ${PRIVATE_KEY}
  valid-duration: 3600 #in second
  refreshable-duration: 360000 # in second

fileUpload:
  rootPath: D:\uploads

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-southeast-1
    endpointUrl: https://s3.ap-southeast-1.amazonaws.com

application:
  bucket:
    name: uploadfileimage
